"""Source registry: which sources cover a window, from a generated coverage index.

Two files (sites/):
  sources.yml               hand-edited definitions: kind, URL, field mapping, notes. Optional ``coverage``:
                            ``auto`` (default for arcgis: from the service), ``nz``, ``global``, or a bbox
                            [lon_min, lat_min, lon_max, lat_max] (EPSG:4326).
  sources_coverage.geojson  generated by ``scripts/index_sources.py``: one feature per source, its
                            coverage in EPSG:4326 and what it provides. For ArcGIS layers the coverage is
                            the 1:10k LINZ tiles (4.8 x 7.2 km, the processing unit) where the layer has
                            features, with counts: counted per 1:50k sheet first, then per tile inside the
                            sheets that have any. A district's (or KiwiRail's national) bounding box does
                            not claim tiles without features.

A site with ``sources: auto`` (or no ``sources``) gets every enabled source whose coverage meets its
window, optionally limited by ``layers:`` and ``exclude:``; an explicit list still works.
"""
from __future__ import annotations

import datetime as _dt
import json
from pathlib import Path

NZ_LONLAT = (165.8, -47.4, 179.0, -34.0)        # main islands and Stewart Island (Chathams excluded)
GLOBAL_LONLAT = (-180.0, -90.0, 180.0, 90.0)
OSM_LAYERS = ["roads", "rail", "waterways", "culverts", "buildings"]
NATIONAL_KINDS = {"linz_wfs": "nz", "osm": "global"}


def provides(spec: dict) -> list[str]:
    """Layer types a source contributes (labels or context)."""
    if spec.get("kind") == "osm":
        return OSM_LAYERS
    return [spec["layer"]] if spec.get("layer") else []


def _lonlat(bounds_2193):
    from rasterio.warp import transform_bounds
    return transform_bounds("EPSG:2193", "EPSG:4326", *bounds_2193, densify_pts=21)


def _extent_lonlat(ext: dict):
    from rasterio.warp import transform_bounds
    sr = ext.get("spatialReference") or {}
    wkid = sr.get("latestWkid") or sr.get("wkid") or 4326
    wkid = 3857 if wkid == 102100 else wkid
    return transform_bounds(f"EPSG:{wkid}", "EPSG:4326", ext["xmin"], ext["ymin"], ext["xmax"], ext["ymax"], densify_pts=21)


def coverage_record(http, name: str, spec: dict, sheets=None, workers: int = 8, log=print, tiles=None,
                    tile_scale: int = 10000) -> dict:
    """One coverage feature (GeoJSON dict) for a source. ``sheets`` / ``tiles`` limit the counts to these
    1:50k sheets and 1:``tile_scale`` tiles (e.g. those of the LiDAR partition); None = all in the extent."""
    from shapely.geometry import box
    from shapely.ops import unary_union

    from .. import grid
    from . import arcgis
    props = dict(name=name, kind=spec.get("kind"), provides=provides(spec), enabled=spec.get("enabled", True) is not False,
                 checked=_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"), url=spec.get("url"))
    cov = spec.get("coverage", NATIONAL_KINDS.get(spec.get("kind"), "auto"))
    if isinstance(cov, (list, tuple)):
        return _feature(box(*cov), props, method="explicit")
    if cov in ("nz", "global"):
        return _feature(box(*(NZ_LONLAT if cov == "nz" else GLOBAL_LONLAT)), props, method=cov)
    if spec.get("kind") != "arcgis":
        return _feature(box(*NZ_LONLAT), props, method="nz (default for this kind)")
    if not str(spec.get("url", "")).startswith(("http://", "https://")) and not arcgis.HUB_ITEM.match(str(spec.get("url", ""))):
        return _feature(box(*NZ_LONLAT), dict(props, note=f"url not resolved: {spec.get('url')!r}"), method="unresolved")
    url, _ = arcgis.first_working(http, spec)
    meta = http.json(url, {"f": "json"})
    ext = meta.get("extent")
    if not ext:
        return _feature(box(*NZ_LONLAT), dict(props, note="layer reports no extent"), method="nz (no extent)")
    ll = _extent_lonlat(ext)
    from rasterio.warp import transform_bounds
    e2193 = transform_bounds("EPSG:4326", "EPSG:2193", *ll, densify_pts=21)
    cand = grid.NZSheetGrid(50000).tiles(e2193)
    if sheets is not None:
        cand = [s for s in cand if s in sheets]
    where = spec.get("where", "1=1")

    def one(t):
        try:
            return t, arcgis.count(http, url, grid.tile_bounds(t), where)[0], None
        except Exception as e:  # noqa: BLE001
            return t, None, str(e)

    def counts_for(ids):
        from concurrent.futures import ThreadPoolExecutor
        with ThreadPoolExecutor(max_workers=workers) as ex:
            res = list(ex.map(one, ids))
        return {t: n for t, n, _ in res if n}, [t for t, n, e in res if e]
    sheet_counts, failed = counts_for(cand)
    tile_ids = [t for sh in sheet_counts for t in grid.children(sh, tile_scale) if tiles is None or t in tiles]
    tile_counts, failed_t = counts_for(tile_ids) if tile_ids else ({}, [])
    failed += failed_t
    log(f"  {name}: extent covers {len(cand)} sheet(s); features in {len(sheet_counts)} sheet(s), "
        f"{len(tile_counts)} of {len(tile_ids)} 1:{tile_scale} tiles" + (f"; {len(failed)} queries failed" if failed else ""))
    cells = tile_counts or sheet_counts
    geom = unary_union([box(*_lonlat(grid.tile_bounds(t))) for t in cells]) if cells else box(*ll)
    return _feature(geom, dict(props, extent=list(ll), sheets=sheet_counts, tiles=tile_counts, tile_scale=tile_scale,
                               n_features=sum(sheet_counts.values()), failed=failed, layer_url=url),
                    method="tiles" if tile_counts else "sheets" if sheet_counts else "extent (no features counted)")


def _feature(geom, props, method):
    from shapely.geometry import mapping
    return {"type": "Feature", "properties": dict(props, coverage=method), "geometry": mapping(geom)}


def write_index(features, path):
    path = Path(path)
    path.write_text(json.dumps({"type": "FeatureCollection", "name": "sources_coverage",
                                "generated_by": "scripts/index_sources.py", "features": features}, indent=1))


def load_index(path) -> dict:
    """{name: (shapely geometry in EPSG:4326, properties)}."""
    from shapely.geometry import shape
    d = json.loads(Path(path).read_text())
    return {f["properties"]["name"]: (shape(f["geometry"]), f["properties"]) for f in d["features"]}


def resolve(sources: dict, index: dict, window_2193, layers=None, exclude=()) -> list[str]:
    """Names of enabled sources whose coverage meets the window (and provide one of ``layers``)."""
    from shapely.geometry import box
    w = box(*_lonlat(window_2193))
    missing = [n for n, s in sources.items() if s.get("enabled", True) is not False and n not in index]
    if missing:
        raise ValueError(f"not in the coverage index (run scripts/index_sources.py): {', '.join(missing)}")
    out = []
    for name, spec in sources.items():
        if spec.get("enabled", True) is False or name in exclude:
            continue
        if layers and not set(provides(spec)) & set(layers):
            continue
        geom, _ = index[name]
        if geom.intersects(w):
            out.append(name)
    return out


def default_index_path(sources_path) -> Path:
    return Path(sources_path).with_name("sources_coverage.geojson")
